'use strict';
// Every number on the page comes from here. Update it with the change that affects it (see AGENTS.md).
/* ---------------- DATA (all collected from the repo, git and gh) ---------------- */
const D = {
  license: 'Apache-2.0',
  areas: [
    {
      id: 'renderer',
      label: 'renderer (root)',
      proc: 'renderer',
      files: 6,
      tests: 2,
      lines: 1045,
      testLines: null,
      desc: 'UI entry point and shell: App, the h() DOM builder, HTML-only Markdown rendering (DOMPurify; no SVG/MathML), formatting, error reporting.',
      list: [
        'app.ts (827; resets panels only when the active project path changes, #160)',
        'main.ts',
        'dom.ts (h(), trustedHtml)',
        'markdown.ts (48, HTML-only model output)',
        'format.ts',
        'error_reporting.ts',
      ],
    },
    {
      id: 'views',
      label: 'renderer/views',
      proc: 'renderer',
      files: 5,
      tests: 2,
      lines: 2557,
      testLines: null,
      desc: 'Screens: transcript, composer with @-mentions, sidebar, terminal/browser/git panels, settings and history dialogs.',
      list: [
        'dialogs.ts (742, untested)',
        'panels.ts (648, untested)',
        'transcript.ts (572, untested)',
        'composer.ts (395)',
        'sidebar.ts',
      ],
    },
    {
      id: 'preload',
      label: 'preload',
      proc: 'preload',
      files: 2,
      tests: 0,
      lines: 37,
      testLines: 0,
      desc: 'Typed bridge. Only exposes invoke/on, allow-listed by INVOKE_CHANNELS / EVENT_CHANNELS from shared/ipc.ts.',
      list: ['index.ts', 'api.d.ts'],
    },
    {
      id: 'mainroot',
      label: 'main (root)',
      proc: 'main',
      files: 14,
      tests: 10,
      lines: 2408,
      testLines: 2403,
      desc: 'App wiring: IPC handlers, program lookup that never searches the project folder (#141), ChatManager, chat storage, settings with native confirmation for changes to protective permission rules or their prefixes, projects, window, menu, local error and native-crash logging.',
      list: [
        'chat_manager.ts (505; prepares restored sessions against target resources before switching, #161; same-project state, #160; custom-endpoint finder model, #203)',
        'index.ts (458; history errors resync the renderer, #161; terminal survives same-project navigation, #160)',
        'exec_search.ts (37, bare program names never resolve in the project, #141)',
        'settings.ts (451)',
        'chat_store.ts (182)',
        'app_log.ts (error + crash logging)',
        'settings_confirm.ts (182, ordered protective-rule confirmation)',
        'projects.ts',
        'files.ts',
        'ipc.ts',
        'menu.ts',
        'window.ts',
        'renderer_errors.ts',
        'renderer_url.ts',
      ],
    },
    {
      id: 'agent',
      label: 'main/agent',
      proc: 'main',
      files: 10,
      tests: 11,
      lines: 1609,
      testLines: 3366,
      desc: 'The agent loop: turns, retries, permissions, allow-lists, system prompt, project map, session (approvals, events, prompt-cache keep-alive).',
      list: [
        'agent.ts (530; malformed JSON rejected before dropped-field checks, #179)',
        'session.ts (490)',
        'permissions.ts',
        'allowed_commands.ts',
        'allowed_network_hosts.ts',
        'retry.ts',
        'system_prompt.ts',
        'project_map.ts',
        'agent_file.ts',
        'tool_error_log.ts',
      ],
    },
    {
      id: 'llm',
      label: 'main/llm',
      proc: 'main',
      files: 11,
      tests: 8,
      lines: 2134,
      testLines: 2769,
      desc: 'Provider clients: Anthropic Messages with strict edit inputs, OpenAI Responses with backend-specific truncation (omitted for ChatGPT subscriptions), OpenAI-compatible Chat Completions, plus compaction, ChatGPT sign-in and guarded endpoints.',
      list: [
        'codex_auth.ts (477, ChatGPT sign-in)',
        'anthropic.ts (422, prompt cache, keep-alive)',
        'openai.ts (295)',
        'openai_responses.ts (294, platform/Codex requests)',
        'index.ts (LlmService)',
        'endpoints.ts (test hooks off in packaged builds)',
        'compaction.ts',
        'openai_route.ts',
        'tool_schema.ts',
        'types.ts',
        'test_server.ts',
      ],
    },
    {
      id: 'tools',
      label: 'main/tools',
      proc: 'main',
      files: 23,
      tests: 23,
      lines: 4005,
      testLines: 5953,
      desc: 'Every model tool, plus fail-closed command sandboxes, a minimal native environment with native-confirmed extra variable/PATH settings (#95), credential-safe toolchain grants, package-aware Program Files toolchains with no-admin read-only staging and journaled copy cleanup (#106), protected Git metadata, Workspace.resolve confinement, protected-file guards, redaction, MCP and subagents. Non-Git folders, Husky and in-project gitfiles/shared metadata run sandboxed (#109); external metadata and writable config includes still refuse execution. Git writes need the panel or unsandboxed approval, which states loss of file confinement and unrestricted networking. Matching URLs request unrestricted network, not hostname filtering. Windows commands get private journaled temp/npm-cache roots, project PATH mapping and process-only PowerShell script policy; old Node pipe handling remains upstream (#101), so a sandboxed timeout tells the agent about the workaround. Project drive mappings are journaled before creation and recovered by exact letter/target after a crash (#94).',
      list: [
        'registry.ts',
        'shell.ts (504; streaming UTF-8 output, #164; sandbox-only PowerShell imports and script policy; Windows-sandbox timeout hint for the Node test hang, #101; awaits sandbox probes in prepare)',
        'sandbox_windows.ts (402, Program Files candidates, protected Git paths, helper protocol and the project-grant revoke on close, #103)',
        'sandbox.ts (476; exact-name Seatbelt Mach, sysctl and IPC grants; asynchronous, mode-scoped support probes, #112)',
        'files.ts (349; read_file line counts, #181; UTF-8-only edits and overwrites, #159)',
        'web.ts (226, no own test)',
        'sandbox_windows.integration.test.ts (real AppContainer temp/cache writes, Node/npm tests and upstream skips, toolchains, overlapping project-drive and ACL recovery)',
        'sandbox.integration.test.ts (native/container environment isolation and production ShellRunner grants)',
        'sandbox_git.ts (210; a .git reservation file Git refuses (an empty folder plus a protected HEAD folder inside another repository), confined metadata pointers, trusted system links above the project and protected includes)',
        'sandbox_git.integration.test.ts (no Git, Husky, gitfiles/worktrees, metadata write and hard-link denial)',
        'sandbox_macos.integration.test.ts (real Seatbelt Mach-service, LaunchServices, network-off local endpoint, shared-memory, semaphore and sysctl probes; skipped off macOS)',
        'env.ts (minimal native allow-list; built-in PowerShell module path; inherited startup/agent handles blocked)',
        'apply_patch.ts (286; same-path moves, #183; rejects non-UTF-8 updates before any write, #159)',
        'glob.ts',
        'regex_worker.ts (grep/glob patterns off the main process)',
        'browser.ts',
        'mcp.ts',
        'task.ts',
        'todo.ts',
        'plan.ts',
        'skills.ts',
        'guard.ts',
        'redact.ts',
        'workspace.ts',
        'edit_backups.ts',
        'text_files.ts',
        'types.ts',
        'native/sandbox-helper/src/win.rs (2621; project drive ownership, 8.3-alias-safe path mapping, ACL coordination, crash recovery, the cross-command toolchain cache, #108, and the once-per-project capability grant, #103; 34 Rust helper tests plus 1 CI-preparation test pass)',
      ],
    },
    {
      id: 'panels',
      label: 'main/panels',
      proc: 'main',
      files: 4,
      tests: 4,
      lines: 607,
      testLines: 914,
      desc: 'Back ends for the side panels: terminal (node-pty), browser, git (simple-git), commit message suggestion.',
      list: [
        'terminal.ts',
        'browser.ts',
        'git.ts (385; link-safe discard, hook/filter hardening, implicit bare-repository discovery refusal and no project-file credential/SSH/signing programs on push or commit)',
        'commit_message.ts',
      ],
    },
    {
      id: 'search',
      label: 'main/search',
      proc: 'main',
      files: 2,
      tests: 1,
      lines: 440,
      testLines: 347,
      desc: 'Embedding code index for the search_code tool: Voyage voyage-code-4 embeddings and rerank-3 reranking through OpenRouter.',
      list: ['code_index.ts (single index refresh per search with progress, #186; 411)', 'chunker.ts'],
    },
    {
      id: 'storage',
      label: 'main/storage',
      proc: 'main',
      files: 2,
      tests: 1,
      lines: 132,
      testLines: 101,
      desc: 'Atomic JSON writes (temp file + rename, background writes for checkpoints), reads that set an unparseable file aside as .corrupt-<timestamp> (#168), and JSONL logs.',
      list: ['json_file.ts', 'jsonl_log.ts'],
    },
    {
      id: 'shared',
      label: 'shared',
      proc: 'shared',
      files: 9,
      tests: 8,
      lines: 1243,
      testLines: 852,
      desc: 'Types and logic used by both sides: IPC contract, chat events, models, settings, panels, export.',
      list: [
        'chat.ts (335)',
        'ipc.ts (201)',
        'models.ts',
        'settings.ts (sandboxEnvAllowList and sandboxPath default empty; global native-confirmed grants)',
        'project.ts',
        'panels.ts',
        'export.ts',
        'announce.ts',
        'index_status.ts',
      ],
    },
  ],
  edges: [
    ['mainroot', 'tools', 14],
    ['mainroot', 'agent', 9],
    ['mainroot', 'panels', 4],
    ['mainroot', 'storage', 4],
    ['mainroot', 'llm', 3],
    ['mainroot', 'search', 1],
    ['agent', 'tools', 7],
    ['agent', 'llm', 3],
    ['agent', 'storage', 1],
    ['tools', 'llm', 4],
    ['tools', 'agent', 1],
    ['search', 'tools', 3],
    ['search', 'storage', 1],
    ['panels', 'tools', 2],
    ['panels', 'llm', 1],
    ['llm', 'mainroot', 1],
    ['views', 'renderer', 10],
    ['renderer', 'views', 5],
  ],
  sharedEdges: [
    ['mainroot', 16],
    ['views', 13],
    ['renderer', 8],
    ['agent', 6],
    ['llm', 4],
    ['tools', 3],
    ['panels', 1],
    ['search', 1],
    ['preload', 1],
  ],
  ipc: {
    invoke: [
      ['project', 9],
      ['chat', 8],
      ['git', 8],
      ['history', 5],
      ['settings', 3],
      ['chatgpt', 2],
      ['files', 3],
      ['terminal', 3],
      ['index', 2],
      ['app', 1],
      ['log', 1],
      ['mcp', 1],
      ['edit', 1],
    ],
    invokeNames: {
      project: 'choose, open, current, list, opened, close, set-instructions, update-settings, remove',
      chat: 'snapshot, send, stop, resume, compact, new, decide, export',
      git: 'status, diff, commit, discard, discard-all, init, push, suggest-message',
      history: 'list, open, delete, clear, search',
      settings: 'get, update, set-secret',
      chatgpt: 'sign-in, sign-out',
      files: 'pick-images, open-in-editor, list',
      terminal: 'start, write, resize',
      index: 'status, rebuild',
      app: 'info',
      log: 'renderer-error',
      mcp: 'status',
      edit: 'undo',
    },
    events: [
      'menu:command',
      'app:notice',
      'settings:changed',
      'project:changed',
      'chat:event',
      'chat:snapshot',
      'history:changed',
      'terminal:data',
      'terminal:exit',
      'panel:show',
    ],
  },
  chatEvents: {
    User: ['user'],
    'Assistant text': ['assistant-start', 'assistant-delta', 'thinking-delta', 'assistant-restart', 'assistant-end'],
    Tools: ['tool-start', 'tool-running', 'tool-progress', 'tool-end', 'tool-undone'],
    Messages: ['error', 'notice'],
    State: ['busy', 'resumable', 'usage', 'title'],
  },
  tools: [
    ['read_file', 'files.ts', 0, 0, 'always'],
    ['list_directory', 'files.ts', 0, 0, 'always'],
    ['grep', 'files.ts', 0, 0, 'always'],
    ['glob', 'glob.ts', 0, 0, 'always'],
    ['edit_file', 'files.ts', 1, 0, 'always'],
    ['write_file', 'files.ts', 1, 0, 'always'],
    ['apply_patch', 'apply_patch.ts', 1, 0, 'always'],
    ['run_command', 'shell.ts', 1, 0, 'always'],
    ['command_output', 'shell.ts', 0, 0, 'always'],
    ['fetch_url', 'web.ts', 1, 0, 'always'],
    ['web_search', 'web.ts', 0, 0, 'web search provider set'],
    ['browser', 'browser.ts', 1, 0, 'browser panel available'],
    ['propose_plan', 'plan.ts', 1, 1, 'always (asks only while plan mode is on)'],
    ['load_skill', 'skills.ts', 0, 0, 'project has skills'],
    ['search_code', 'search/code_index.ts', 0, 0, 'code index available (per chat)'],
    ['task', 'task.ts', 0, 0, 'per chat (subagent)'],
    ['finder', 'task.ts', 0, 0, 'per chat (subagent)'],
    ['oracle', 'task.ts', 0, 0, 'per chat (subagent)'],
    ['todo_list', 'todo.ts', 0, 0, 'per chat'],
    ['mcp_<server>_<tool>', 'mcp.ts (McpHub)', 1, 1, 'one per MCP server tool'],
  ],
  readOnly: ['read_file', 'list_directory', 'grep', 'glob', 'search_code', 'load_skill'],
  npmDeps: 9,
  npmDev: 28,
  models: {
    anthropic: ['claude-opus-5-5 (default)', 'claude-sonnet-5-5', 'claude-haiku-4-5 (small)'],
    openai: ['gpt-6-astra', 'gpt-6-sol', 'gpt-6-luna (small)'],
  },
  testsByArea: [
    { a: 'main/agent', f: 11, c: 213, src: 1609, tl: 3366 },
    { a: 'main/llm', f: 8, c: 97, src: 2134, tl: 2769 },
    { a: 'main/tools', f: 23, c: 434, src: 4005, tl: 5953 },
    { a: 'main/panels', f: 4, c: 63, src: 607, tl: 914 },
    { a: 'main/other', f: 12, c: 180, src: 2960, tl: 2831 },
    { a: 'shared', f: 8, c: 73, src: 1243, tl: 852 },
    { a: 'renderer', f: 4, c: 14, src: 6368, tl: 138 },
    { a: 'preload', f: 0, c: 0, src: 37, tl: 0 },
  ],
  e2e: [
    ['security', 12],
    ['chat', 11],
    ['ui', 12],
    ['panels', 7],
    ['sandbox_approvals', 8],
    ['logging', 5],
    ['compact', 4],
    ['project_settings', 4],
    ['project_switching', 7],
    ['settings', 6],
    ['undo', 4],
    ['images', 3],
    ['projects', 3],
    ['retry', 3],
    ['transcript_view', 3],
    ['crash_kill', 2],
    ['documentation-visuals', 2],
    ['large_output', 2],
    ['long_run', 2],
    ['openai_responses', 4],
    ['secrets_restart', 2],
    ['crash_resume', 1],
    ['grep_redos', 1],
    ['mcp', 1],
    ['plan_mode', 1],
    ['resume', 1],
    ['single_instance', 1],
    ['skills', 1],
    ['task', 1],
    ['terminal_no_project', 1],
    ['planted_binaries', 1],
  ],
  untested: [
    [826, 'renderer/src/app.ts'],
    [742, 'renderer/src/views/dialogs.ts'],
    [648, 'renderer/src/views/panels.ts'],
    [572, 'renderer/src/views/transcript.ts'],
    [446, 'main/index.ts'],
    [334, 'main/tools/files.ts *'],
    [226, 'main/tools/web.ts *'],
    [201, 'shared/ipc.ts'],
  ],
  largest: [
    [826, 'renderer/src/app.ts'],
    [742, 'renderer/src/views/dialogs.ts'],
    [648, 'renderer/src/views/panels.ts'],
    [572, 'renderer/src/views/transcript.ts'],
    [530, 'main/agent/agent.ts'],
    [490, 'main/agent/session.ts'],
    [480, 'main/chat_manager.ts'],
    [477, 'main/llm/codex_auth.ts'],
    [493, 'main/tools/shell.ts'],
    [451, 'main/settings.ts'],
    [445, 'main/tools/sandbox.ts'],
    [446, 'main/index.ts'],
    [422, 'main/llm/anthropic.ts'],
    [411, 'main/search/code_index.ts'],
    [395, 'renderer/src/views/composer.ts'],
  ],
  docs: [
    ['docs/PERFORMANCE.md', 461],
    ['docs/USAGE.md', 292],
    ['docs/ARCHITECTURE.md', 252],
    ['docs/DEVELOPMENT.md', 203],
    ['CHANGELOG.md', 195],
    ['README.md', 142],
    ['AGENTS.md', 77],
    ['CONTRIBUTING.md', 33],
    ['LICENSE (Apache-2.0)', 202],
    ['LICENSE-MIT (historical notice)', 21],
  ],
  commitsByDay: [
    ['2024-07-29', 3],
    ['2026-09-29', 67],
    ['2026-09-30', 99],
    ['2026-10-01', 33],
    ['2026-10-02', 15],
    ['2026-10-03', 24],
    ['2026-10-04', 32],
    ['2026-10-05', 17],
    ['2026-10-06', 43],
    ['2026-10-07', 20],
    ['2026-10-08', 7],
  ],
  types: [
    ['fix', 120],
    ['docs', 71],
    ['feat', 60],
    ['test', 41],
    ['chore', 27],
    ['perf', 14],
    ['ci', 9],
    ['other', 8],
    ['refactor', 6],
    ['build', 3],
    ['security', 1],
  ],
  authors: [
    ['PierrunoYT', 291],
    ['Amp', 28],
    ['StepUpGaming', 23],
    ['Claude', 7],
    ['Huanyi Xie', 6],
    ['Steven Isaac', 3],
    ['reason-machines[bot]', 1],
    ['patchmote[bot]', 1],
  ],
  churn: [
    ['CHANGELOG.md', 217],
    ['docs/ARCHITECTURE.md', 138],
    ['docs/DEVELOPMENT.md', 119],
    ['README.md', 113],
    ['TASKS.md (no longer tracked)', 83],
    ['docs/USAGE.md', 55],
    ['patch-overview.html (now project-map/)', 52],
    ['package.json', 46],
    ['src/main/chat_manager.ts', 41],
    ['src/main/index.ts', 40],
    ['src/main/agent/agent.ts', 33],
    ['src/renderer/src/app.ts', 30],
    ['package-lock.json', 27],
    ['src/renderer/src/views/dialogs.ts', 26],
    ['docs/PERFORMANCE.md', 26],
    ['src/main/tools/tools.test.ts', 26],
    ['src/main/tools/shell.ts', 24],
    ['src/main/agent/session.ts', 24],
    ['src/main/tools/sandbox_windows.integration.test.ts', 22],
    ['src/main/agent/agent.test.ts', 22],
  ],
  recent: [
    ['838d396', 'fix: preserve panels during same-project navigation (#160)'],
    ['a1e0d11', 'fix: reject non-UTF-8 file edits and overwrites (#159)'],
    ['ec64562', 'docs: tidy the changelog and README after merging #212-#217'],
    ['04ea96f', 'fix: preserve the chat model for finder on custom Anthropic endpoints (#217)'],
    ['dce78c4', 'fix: report malformed tool-call JSON before schema validation (#216)'],
    ['c2fd198', 'fix: decode command output across UTF-8 chunk boundaries (#215)'],
    ['a0e6262', 'perf: refresh the code index once per search (#214)'],
    ['cc19664', 'fix: treat same-path patch moves as updates (#213)'],
    ['7060c8b', 'fix: count terminated file lines and reject out-of-range reads (#212)'],
    ['a2eef6e', 'fix: never resolve bare program names in the project folder'],
    ['71bafa4', 'docs: track the remaining findings from the earlier security reports (#207-#211)'],
    ['a0af423', 'docs: track the code review improvements (#197-#206) and label fixes'],
    ['23b8cad', 'docs: track the low-severity code review findings (#179-#196)'],
    ['b791d49', 'docs: track the Oct 7 code review findings (#159-#178)'],
    ['3eb6f25', 'docs: track the Oct 7 security audit findings (#141-#158)'],
    ['928463c', 'docs: track the Windows sandbox follow-ups to #103'],
    ['fd7a895', 'perf: grant the Windows sandbox project once instead of per command'],
    ['3a1eb94', 'test: load the Windows sandbox suite on platforms without LOCALAPPDATA'],
    ['7778e01', 'fix: keep Windows sandbox toolchain copies across commands'],
  ],
  issues: [
    [218, 'e2e: macOS UI and project-tab tests time out intermittently on CI', 'tests', 'low', 0, '10-08'],
    [211, 'Build-time dependency advisories in electron-builder and vite', 'release', 'low', 0, '10-07'],
    [210, 'ChatGPT sign-in: redirect says localhost, server binds only 127.0.0.1', 'security', 'low', 0, '10-07'],
    [209, 'openInEditor runs the editor command through a shell', 'security', 'low', 0, '10-07'],
    [208, 'Renderer h() sets any known DOM property from props', 'security', 'low', 0, '10-07'],
    [207, 'Windows sandbox: toolchain access granted on the shared Program Files folder', 'sandbox', 'low', 0, '10-07'],
    [206, 'Sandbox helper: long paths; revoke requests on the input thread', 'sandbox', 'low', 0, '10-07'],
    [205, 'Small cleanups in command and panel code', 'other', 'low', 0, '10-07'],
    [204, 'Offer Resume after a run fails once its retries are used up', 'ui', 'low', 0, '10-07'],
    [202, 'ChatGPT sign-in: keep-cache-warm does nothing; no refresh after a 401', 'other', 'low', 0, '10-07'],
    [201, 'Reuse regex workers across grep and glob calls', 'perf', 'low', 0, '10-07'],
    [200, 'Rendering cost grows with transcript length while an answer streams', 'perf', 'low', 0, '10-07'],
    [199, 'Reuse one GitService per project instead of one per IPC call', 'perf', 'low', 0, '10-07'],
    [198, 'grep and glob: missing-path errors and backslash patterns on Windows', 'tools', 'low', 0, '10-07'],
    [197, 'apply_patch changes have no Undo', 'tools', 'low', 0, '10-07'],
    [196, 'Test gaps from the code review: fakes, snapshot-only e2e checks, sleeps', 'tests', 'low', 0, '10-07'],
    [195, 'Sandbox helper: exit code 259, .git restore, Started order, env sort', 'sandbox', 'low', 0, '10-07'],
    [194, 'Composer and git panel state races (stale mentions, cleared input)', 'ui', 'low', 0, '10-07'],
    [193, 'Renderer actions that fail silently or run twice (delete, commit)', 'ui', 'low', 0, '10-07'],
    [192, 'Renderer can miss chat events sent during startup', 'ui', 'low', 0, '10-07'],
    [191, 'Terminal drops keys typed before the shell is ready; blank after reopen', 'ui', 'low', 0, '10-07'],
    [190, 'Quitting while an MCP server connects keeps the app running up to 20 s', 'mcp', 'low', 0, '10-07'],
    [189, 'fetch_url: timeout aborts a slow body read; charset is ignored', 'tools', 'low', 0, '10-07'],
    [188, 'Unbounded waits: revokeProjectGrant, timed-out browser waiters', 'other', 'low', 0, '10-07'],
    [187, 'Background commands stay in memory; their IDs are shared across chats', 'tools', 'low', 0, '10-07'],
    [185, 'Windows path casing duplicates projects, read tracking and indexes', 'other', 'low', 0, '10-07'],
    [184, 'Settings validation gaps (max indexed files 1, base URL, MCP values)', 'other', 'low', 0, '10-07'],
    [182, 'Mixed line endings: apply_patch rewrites LF as CRLF; edit_file misses', 'tools', 'low', 0, '10-07'],
    [180, 'Exhausted pause_turn continuations end the turn silently', 'other', 'low', 0, '10-07'],
    [178, 'Permission delegates fail on Windows for .cmd/.bat and take no arguments', 'security', 'medium', 0, '10-07'],
    [177, 'Windows sandbox: concurrent commands run out of drive letters', 'sandbox', 'medium', 0, '10-07'],
    [176, 'Windows sandbox: first grant in a large project outlasts the 60 s lock', 'sandbox', 'medium', 0, '10-07'],
    [175, 'Pasting text that also carries an image drops the text', 'ui', 'medium', 0, '10-07'],
    [174, 'Git panel diff and Discard fail when the project is a repo subfolder', 'ui', 'medium', 0, '10-07'],
    [173, 'Anthropic: mid-stream connection drops are retried at once, without notice', 'other', 'medium', 0, '10-07'],
    [172, 'Subagent token usage is priced at the chat model’s rate', 'other', 'medium', 0, '10-07'],
    [171, 'trimHistory is quadratic and blocks the main process on long chats', 'perf', 'medium', 0, '10-07'],
    [170, 'Code index: lost progress, shared stop, duplicate runs on settings change', 'tools', 'medium', 0, '10-07'],
    [169, 'Ignore rules go stale; nested .gitignore files are ignored', 'tools', 'medium', 0, '10-07'],
    [167, 'write_file overwrites changes made after the agent read the file', 'tools', 'medium', 0, '10-07'],
    [166, 'MCP server that dies after connecting stays "connected" forever', 'mcp', 'medium', 0, '10-07'],
    [165, 'Processes a command leaves behind are never killed on Stop or quit', 'tools', 'medium', 0, '10-07'],
    [163, 'Windows sandbox: an unreadable PATH folder breaks every later helper start', 'sandbox', 'high', 0, '10-07'],
    [162, 'Windows sandbox: a command failing before start leaves the helper running', 'sandbox', 'high', 0, '10-07'],
    [158, 'Windows sandbox hardening: LPAC, separate desktop, safe DLL search', 'sandbox', 'low', 0, '10-07'],
    [
      157,
      'Renderer can start a shell and edit instructions without native confirmation',
      'security',
      'low',
      0,
      '10-07',
    ],
    [156, 'Git panel commit check misses gpg.ssh.defaultKeyCommand', 'security', 'low', 0, '10-07'],
    [155, 'Allowed-command prefixes also allow flags that write files', 'security', 'low', 0, '10-07'],
    [154, 'Code indexer follows a swapped symlink and embeds outside content', 'security', 'low', 0, '10-07'],
    [153, 'Environment scrubbing and secret redaction are deny-lists', 'security', 'low', 0, '10-07'],
    [152, 'Windows sandbox: one unreadable recovery record disables the sandbox', 'sandbox', 'low', 0, '10-07'],
    [151, 'Windows sandbox: toolchain cache readable by every AppContainer', 'sandbox', 'low', 0, '10-07'],
    [150, 'Windows sandbox: memory and CPU limits apply per process, not per job', 'sandbox', 'low', 0, '10-07'],
    [149, 'Packaged builds look for sandbox-helper.exe in dev paths and the cwd', 'sandbox', 'low', 0, '10-07'],
    [148, 'Browser tool uses the panel’s persistent cookie session', 'security', 'medium', 0, '10-07'],
    [147, 'macOS sandboxed commands with network can reach local Unix sockets', 'sandbox', 'medium', 0, '10-07'],
    [
      146,
      'fetch_url and browser reach any address in Auto mode (SSRF, exfiltration)',
      'security',
      'medium',
      0,
      '10-07',
    ],
    [
      145,
      'Opening the home folder as a project makes all of it writable to the sandbox',
      'sandbox',
      'high',
      0,
      '10-07',
    ],
    [144, 'File tools check a path, then write it later: a swapped symlink redirects', 'security', 'high', 0, '10-07'],
    [143, 'Protected-path guard misses case variants and 8.3 names (.GIT/config)', 'security', 'high', 0, '10-07'],
    [142, 'MCP stdio servers can start a program planted in the project', 'mcp', 'high', 0, '10-07'],
    [
      140,
      'Windows sandbox: files moved into a project lack its write grant until reopened',
      'sandbox',
      'low',
      0,
      '10-07',
    ],
    [139, 'Windows sandbox: .git permissions are still walked several times per command', 'sandbox', 'low', 0, '10-07'],
    [
      138,
      'e2e: crash_kill approval test stalls on CI (chat save and Local State never written)',
      'tests',
      'medium',
      0,
      '10-07',
    ],
    [135, 'Agent benchmark: a current baseline, more runs per task and regression checks', 'tests', 'low', 0, '10-06'],
    [
      133,
      'Windows toolchain tests leak subst drives after the temp Node fixture is deleted',
      'tests',
      'low',
      0,
      '10-06',
    ],
    [128, 'Isolate built-in file tools behind an OS-restricted executor', 'sandbox', 'medium', 0, '10-06'],
    [127, 'Protect agent, IDE and shell configuration from command writes', 'sandbox', 'medium', 0, '10-06'],
    [126, 'Approve per-command read-only and read/write path grants', 'sandbox', 'low', 0, '10-06'],
    [125, 'e2e: transcript_view approval-card and Undo tests fail intermittently', 'tests', 'low', 0, '10-06'],
    [124, 'Atomic JSON writes use predictable temp names, leave .tmp after a crash', 'security', 'low', 0, '10-06'],
    [121, 'Perplexity Decider V1 27B (OpenRouter) as a safety check on tool calls', 'tools', 'low', 0, '10-05'],
    [120, 'Hide DevTools in packaged builds; delete the webview allowpopups value', 'security', 'low', 0, '10-05'],
    [119, 'ci: restrict GITHUB_TOKEN permissions in ci.yml and run npm audit', 'release', 'low', 0, '10-05'],
    [118, 'Full chat saves are synchronous and pretty-printed on the main process', 'perf', 'low', 0, '10-05'],
    [117, 'Stopping an MCP stdio server kills only its direct child on macOS/Linux', 'mcp', 'low', 0, '10-05'],
    [112, 'Sandbox detection and .git validation block the main process', 'perf', 'medium', 0, '10-05'],
    [105, 'Plan-mode benchmark: multi-step tasks, a mid-run toggle, more models', 'tests', 'low', 0, '10-05'],
    [104, 'No process or memory limits for sandboxed commands on Linux and macOS', 'sandbox', 'low', 0, '10-05'],
    [102, 'Linux sandbox with network reaches abstract sockets and host loopback', 'sandbox', 'medium', 0, '10-05'],
    [101, 'npm test fails and node --test hangs inside the AppContainer', 'sandbox', 'medium', 0, '10-05'],
    [97, 'Enforce hostname restrictions for sandbox command networking', 'sandbox', 'low', 0, '10-04'],
    [96, 'Narrow macOS sandbox file access, isolate command temp directories', 'sandbox', 'medium', 0, '10-04'],
    [87, 'Sandbox MCP stdio servers like agent commands', 'mcp', 'low', 0, '10-04'],
    [85, 'Smarter context: tell the agent what changed since its last turn', 'tools', 'low', 0, '10-03'],
    [84, 'Smarter over time: a project memory the agent can propose additions to', 'tools', 'low', 0, '10-03'],
    [83, 'Smarter finish: review the changes before saying the turn is done', 'tools', 'low', 0, '10-03'],
    [82, 'Smarter navigation: go-to-definition and find-references tools', 'tools', 'low', 0, '10-03'],
    [81, 'Smarter edits: show new compiler and linter errors after each edit', 'tools', 'low', 0, '10-03'],
    [79, 'Faster turns: lower reasoning effort for subagents and simple requests', 'perf', 'low', 0, '10-03'],
    [78, 'Cheaper subagents: run task and oracle on a mid-size model', 'perf', 'low', 0, '10-03'],
    [74, 'Decide whether the release dry run should run on every push to main', 'release', 'low', 0, '10-03'],
    [73, 'web_search sends model-chosen queries to Google without approval', 'security', 'low', 0, '10-01'],
    [72, 'Rename the MCP client from CodeCompanion, use reverse-DNS appId', 'mcp', 'low', 0, '10-01'],
    [71, 'Sign and notarize the macOS build', 'release', 'low', 0, '10-01'],
    [70, 'ci: pin GitHub Actions to commit SHAs', 'release', 'low', 0, '10-01'],
    [67, 'Force webSecurity on browser guests + global web-contents-created guard', 'security', 'low', 0, '10-01'],
    [66, 'IPC sender check accepts any file:///…/renderer/index.html', 'security', 'low', 0, '10-01'],
    [62, 'e2e tests for chat list, header model picker, status-bar branch', 'tests', 'low', 0, '10-01'],
    [50, 'Windows shell cancellation test times out, leaves temp folder locked', 'tests', 'low', 0, '10-01'],
    [49, 'Agent benchmark: per-tool breakdown, other models, harder tasks', 'tests', 'low', 0, '10-01'],
    [47, 'Failed tool cards should say why they failed', 'ui', 'low', 0, '10-01'],
    [46, 'Encourage batching independent tool calls (partly addressed in dfd1f07)', 'perf', 'low', 0, '10-01'],
    [38, 'Rename .ccignore to .patchignore', 'docs', 'low', 0, '09-30'],
    [37, 'Security lint rules, coverage, hostile-repo test', 'tests', 'low', 0, '09-30'],
    [35, 'API keys fall back to plaintext without safeStorage', 'security', 'low', 0, '09-30'],
    [32, 'Validate IPC payloads at runtime with zod', 'security', 'low', 0, '09-30'],
    [28, 'macOS entitlements allow DYLD injection/unsigned exec memory', 'security', 'medium', 0, '09-30'],
    [26, 'Windows builds unsigned (workflow ready, waiting on certificate)', 'release', 'medium', 0, '09-30'],
    [22, 'Hand-test packaged Linux and macOS builds', 'release', 'low', 0, '09-30'],
    [21, 'a11y: test with a real screen reader (NVDA)', 'ui', 'low', 0, '09-30'],
  ],
  themes: {
    sandbox: 'Command sandbox',
    security: 'Security & permissions',
    release: 'Packaging, release & CI',
    tests: 'Tests & benchmarks',
    perf: 'Performance',
    ui: 'UI / UX',
    tools: 'Tools',
    mcp: 'MCP',
    other: 'Bugs',
    docs: 'Docs & naming',
  },
  closedCount: 79,
};
// src/renderer/src/styles.css, counted with the renderer's source lines.
const RENDERER_CSS_LINES = 2766;
// Source lines of one process (renderer, preload, main, shared), summed from its areas.
const procLines = (proc) => D.areas.filter((a) => a.proc === proc).reduce((sum, a) => sum + a.lines, 0);
