'use strict';
// Every number on the page comes from here. Update it with the change that affects it (see AGENTS.md).
/* ---------------- DATA (all collected from the repo, git and gh) ---------------- */
const D = {
  license: 'Apache-2.0',
  areas: [
    {
      id: 'renderer',
      label: 'renderer (root)',
      proc: 'renderer',
      files: 6,
      tests: 4,
      lines: 1137,
      testLines: 171,
      desc: 'UI entry point and shell: App, the h() DOM builder, HTML-only Markdown rendering (DOMPurify; no SVG/MathML), formatting, error reporting.',
      list: [
        'app.ts (865; resets panels only when the active project path changes, #160)',
        'main.ts',
        'dom.ts (h(), trustedHtml)',
        'markdown.ts (86, HTML-only model output; no highlighting while streaming, #200)',
        'format.ts',
        'error_reporting.ts',
      ],
    },
    {
      id: 'views',
      label: 'renderer/views',
      proc: 'renderer',
      files: 5,
      tests: 3,
      lines: 2719,
      testLines: 71,
      desc: 'Screens: transcript, composer with @-mentions, sidebar, terminal/browser/git panels, settings and history dialogs.',
      list: [
        'dialogs.ts (764, untested)',
        'panels.ts (749, untested; the terminal starts on Enter, #157)',
        'transcript.ts (602)',
        'composer.ts (404)',
        'sidebar.ts',
      ],
    },
    {
      id: 'preload',
      label: 'preload',
      proc: 'preload',
      files: 2,
      tests: 0,
      lines: 37,
      testLines: 0,
      desc: 'Typed bridge. Only exposes invoke/on, allow-listed by INVOKE_CHANNELS / EVENT_CHANNELS from shared/ipc.ts.',
      list: ['index.ts', 'api.d.ts'],
    },
    {
      id: 'mainroot',
      label: 'main (root)',
      proc: 'main',
      files: 16,
      tests: 13,
      lines: 2967,
      testLines: 2786,
      desc: 'App wiring: IPC handlers, program lookup that never searches the project folder (#141), ChatManager, chat storage, settings with native confirmation for changes to protective permission rules or their prefixes, projects, window, menu, local error and native-crash logging.',
      list: [
        'chat_manager.ts (547; passes sensitive app paths to ShellRunner, #145; safe restored-session preparation, #161; same-project state, #160)',
        'index.ts (625; one projectSwitched helper for every project switch, History included, #241; Initialize stops sandboxed processes first, #231; native confirmation for the first terminal of each project, #157; sandbox app-data/user-data/install boundaries, #145; history error resync and same-project terminal preservation)',
        'exec_search.ts (37, bare program names never resolve in the project, #141)',
        'settings.ts (484; a fixed-key cipher such as Linux basic_text never counts as encrypted, #258)',
        'chat_store.ts (201; a damaged chat file is skipped when the index is rebuilt, #249)',
        'app_log.ts (error + crash logging)',
        'settings_confirm.ts (226, ordered protective-rule confirmation; every switch to Auto and new project instructions, #157; names the program an MCP server resolves to, #142; unencrypted key save, #35)',
        'projects.ts',
        'files.ts',
        'ipc.ts',
        'ipc_schemas.ts (zod argument schema per invoke channel, #32)',
        'menu.ts',
        'chromium_sandbox.ts (warns when the AppImage launcher dropped the Chromium sandbox, #22)',
        'window.ts',
        'renderer_errors.ts',
        'renderer_url.ts',
      ],
    },
    {
      id: 'agent',
      label: 'main/agent',
      proc: 'main',
      files: 10,
      tests: 11,
      lines: 1887,
      testLines: 3828,
      desc: 'The agent loop: turns, retries, permissions, allow-lists, system prompt, project map, session (approvals, events, prompt-cache keep-alive).',
      list: [
        'agent.ts (596; failed mustAsk checks require approval, #143; malformed JSON rejected before schema checks, #179)',
        'session.ts (526)',
        'permissions.ts (234; rules see project-relative paths, every patched file and each command part, #237)',
        'allowed_commands.ts (43; --output, -o, find -exec and similar arguments always ask, #233)',
        'allowed_network_hosts.ts',
        'retry.ts (Retry-After waits at least a second; long waits leave the chat resumable, #247)',
        'system_prompt.ts',
        'project_map.ts',
        'agent_file.ts',
        'tool_error_log.ts',
      ],
    },
    {
      id: 'llm',
      label: 'main/llm',
      proc: 'main',
      files: 11,
      tests: 8,
      lines: 2218,
      testLines: 3114,
      desc: 'Provider clients: Anthropic Messages with strict edit inputs, OpenAI Responses with backend-specific truncation (omitted for ChatGPT subscriptions), OpenAI-compatible Chat Completions, plus compaction, ChatGPT sign-in and guarded endpoints.',
      list: [
        'codex_auth.ts (507, ChatGPT sign-in)',
        'anthropic.ts (459, prompt cache, keep-alive, Haiku 5.5 per-request price tier)',
        'openai.ts (305)',
        'openai_responses.ts (297, platform/Codex requests)',
        'index.ts (LlmService)',
        'endpoints.ts (test hooks off in packaged builds)',
        'compaction.ts',
        'openai_route.ts',
        'tool_schema.ts',
        'types.ts',
        'test_server.ts',
      ],
    },
    {
      id: 'tools',
      label: 'main/tools',
      proc: 'main',
      files: 28,
      tests: 30,
      lines: 6085,
      testLines: 9121,
      desc: 'Every model tool, plus fail-closed command sandboxes, a minimal native environment with native-confirmed extra variable/PATH settings (#95), credential-safe toolchain grants, package-aware Program Files toolchains with no-admin read-only staging and journaled copy cleanup (#106), protected Git metadata, Workspace.resolve confinement, protected-file guards, redaction, MCP and subagents. Non-Git folders, Husky and in-project gitfiles/shared metadata run sandboxed (#109); external metadata and writable config includes still refuse execution. Git writes need the panel or unsandboxed approval, which states loss of file confinement and unrestricted networking. Allow-list network is enforced by a filtering proxy on Linux and Windows; macOS and containers still request unrestricted network from matching URLs. Windows commands get private journaled temp/npm-cache roots, project PATH mapping and process-only PowerShell script policy; old Node pipe handling remains upstream (#101), so a sandboxed timeout tells the agent about the workaround. Project drive mappings are journaled before creation and recovered by exact letter/target after a crash (#94).',
      list: [
        'registry.ts',
        'shell.ts (746; refuses sensitive roots, #145; project-local macOS temp, #144; streaming UTF-8 and process-tree cleanup; asynchronous sandbox probes)',
        'shell_leftovers.ts (163; finds and kills what a Windows shell left running through its parent pid, #165; lists the process tree of an MCP server it stops, #117)',
        'sandbox_windows.ts (Program Files candidates, protected Git paths, helper protocol (its log events go to the app log, #152), filtered-network proxy pipe, #97, workspace cwd for MCP, #87, and the project-grant revoke on close, #103)',
        'sandbox.ts (safe canonical project roots before Git preparation, #145; project-only Seatbelt writes and command-local temp, #144; asynchronous support probes, #112; bubblewrap in a limited systemd user scope, #104; enforced allow-list on Linux and Windows, #97)',
        'files.ts (393; native no-follow reads and writes, #144; read-before-write and UTF-8-only edits; edit_file refuses a file changed after its preview, #255)',
        'file_operations.ts (104; resource-only packaged helper lookup and original-path native requests, #144)',
        'file_operations.test.ts (161; real helper, batch validation, root aliases and deterministic replacement races)',
        'web.ts (402; fetch_url pins the checked address and keeps redirects on the origin, #146)',
        'net_address.ts (117; local and private address checks for fetch_url and browser, #146)',
        'sandbox_windows.integration.test.ts (real AppContainer temp/cache writes, Node/npm tests and upstream skips, toolchains, overlapping project-drive and ACL recovery)',
        'sandbox.integration.test.ts (native/container environment isolation and production ShellRunner grants)',
        'sandbox_git.ts (313; asynchronous check with a per-project fingerprint cache, #112; a .git reservation file Git refuses (an empty folder plus a protected HEAD folder inside another repository), confined metadata pointers, trusted system links above the project and protected includes)',
        'sandbox_git.integration.test.ts (no Git, Husky, gitfiles/worktrees, metadata write and hard-link denial)',
        'sandbox_macos.integration.test.ts (real Seatbelt Mach-service, LaunchServices, network-off local endpoint, shared-memory, semaphore and sysctl probes; skipped off macOS)',
        'env.ts (minimal native allow-list; built-in PowerShell module path; inherited startup/agent handles blocked)',
        'apply_patch.ts (377; native batched mutations with original paths and byte snapshots, #144; same-path moves and UTF-8 checks; context lines keep the file text, #246; Windows names and case-only duplicates refused up front, #242)',
        'glob.ts',
        'regex_worker.ts (grep/glob patterns off the main process, pooled workers)',
        'browser.ts',
        'mcp.ts (stdio servers start in userData/mcp with an absolute command; ${project} opts a server into the project, #142; stopping one kills its whole process tree, #117; approval cards show the call arguments, #230)',
        'net_proxy.ts (253; host-filtering proxy for allow-list commands on Linux and Windows, #97; CONNECT relays only TLS naming the checked host, #239)',
        'mcp_sandbox.ts (bubblewrap or AppContainer --stdio launch for a stdio server with sandbox: true, fails closed on macOS, #87)',
        'task.ts',
        'todo.ts',
        'plan.ts',
        'skills.ts',
        'guard.ts (protected paths include AGENTS.md, .patch, .envrc and .husky, #236; isSecretPath for indexing, #234)',
        'redact.ts (keys cut by truncation or split between reads, and streamed progress, #253)',
        'workspace.ts (native path canonicalization, including Windows case and short-name aliases, #143; .patchignore with .ccignore fallback, #38)',
        'workspace.test.ts (Windows case and 8.3 regression fixtures; explicit skips on other platforms)',
        'edit_backups.ts',
        'text_files.ts',
        'types.ts',
        'native/sandbox-helper/src/win.rs (independently refuses sensitive roots before ACL changes, #145; project-drive ownership, toolchain cache and per-project grants; the permission lock waits while its holder lives, #176; named-pipe proxy relay, #97; --stdio JSON-RPC passthrough, #87)',
        'native/sandbox-helper/src/file_helper.rs + file_ops/unix.rs + file_ops/windows.rs (no-follow handle-based operations; Unix descriptor and Windows sharing-lock regressions, #144)',
        'native/sandbox-helper/src/net_bridge.rs (forwards 127.0.0.1:3128 in a sandboxed command to the filtering proxy, Unix socket on Linux and named pipe on Windows, #97)',
        'native/sandbox-helper/src/pipe_io.rs (overlapped named-pipe I/O for the Windows network relay, #97)',
        'scripts/build-native.mjs (locked native builds; universal macOS file helper)',
      ],
    },
    {
      id: 'panels',
      label: 'main/panels',
      proc: 'main',
      files: 4,
      tests: 4,
      lines: 802,
      testLines: 1282,
      desc: 'Back ends for the side panels: terminal (node-pty), browser, git (simple-git), commit message suggestion.',
      list: [
        'terminal.ts',
        'browser.ts (193; agent session offline for project files, #229; public pages kept off local addresses and names resolving to them, #235, #260)',
        'git.ts (507; link-safe discard, hook/filter hardening, implicit bare-repository discovery refusal and no project-file credential/SSH/signing programs on push or commit)',
        'commit_message.ts',
      ],
    },
    {
      id: 'search',
      label: 'main/search',
      proc: 'main',
      files: 2,
      tests: 1,
      lines: 580,
      testLines: 606,
      desc: 'Embedding code index for the search_code tool: Voyage voyage-code-4 embeddings and rerank-3 reranking through OpenRouter.',
      list: [
        'code_index.ts (551; single index refresh per search with progress, #186; credential files skipped and secrets masked before embedding, #234; dispose() on a key change, #248)',
        'chunker.ts',
      ],
    },
    {
      id: 'storage',
      label: 'main/storage',
      proc: 'main',
      files: 2,
      tests: 1,
      lines: 225,
      testLines: 232,
      desc: 'Atomic JSON writes (temp file + rename, background writes for checkpoints), reads that set an unparseable file aside as .corrupt-<timestamp> (#168), and JSONL logs.',
      list: ['json_file.ts (fsync before rename, #259)', 'jsonl_log.ts'],
    },
    {
      id: 'shared',
      label: 'shared',
      proc: 'shared',
      files: 9,
      tests: 8,
      lines: 1379,
      testLines: 1089,
      desc: 'Types and logic used by both sides: IPC contract, chat events, models, settings, panels, export.',
      list: [
        'chat.ts (381)',
        'ipc.ts (202)',
        'models.ts',
        'settings.ts (sandboxEnvAllowList and sandboxPath default empty; global native-confirmed grants)',
        'project.ts',
        'panels.ts',
        'export.ts',
        'announce.ts',
        'index_status.ts',
      ],
    },
  ],
  edges: [
    ['mainroot', 'tools', 14],
    ['mainroot', 'agent', 9],
    ['mainroot', 'panels', 4],
    ['mainroot', 'storage', 4],
    ['mainroot', 'llm', 3],
    ['mainroot', 'search', 1],
    ['agent', 'tools', 7],
    ['agent', 'llm', 3],
    ['agent', 'storage', 1],
    ['tools', 'llm', 4],
    ['tools', 'agent', 1],
    ['search', 'tools', 3],
    ['search', 'storage', 1],
    ['panels', 'tools', 2],
    ['panels', 'llm', 1],
    ['llm', 'mainroot', 1],
    ['views', 'renderer', 10],
    ['renderer', 'views', 5],
  ],
  sharedEdges: [
    ['mainroot', 16],
    ['views', 13],
    ['renderer', 8],
    ['agent', 6],
    ['llm', 4],
    ['tools', 3],
    ['panels', 1],
    ['search', 1],
    ['preload', 1],
  ],
  ipc: {
    invoke: [
      ['project', 9],
      ['chat', 8],
      ['git', 8],
      ['history', 5],
      ['settings', 3],
      ['chatgpt', 2],
      ['files', 3],
      ['terminal', 3],
      ['index', 2],
      ['app', 1],
      ['log', 1],
      ['mcp', 1],
      ['edit', 1],
    ],
    invokeNames: {
      project: 'choose, open, current, list, opened, close, update-settings, remove',
      chat: 'snapshot, send, stop, resume, compact, new, decide, export',
      git: 'status, diff, commit, discard, discard-all, init, push, suggest-message',
      history: 'list, open, delete, clear, search',
      settings: 'get, update, set-secret',
      chatgpt: 'sign-in, sign-out',
      files: 'pick-images, open-in-editor, list',
      terminal: 'start, write, resize',
      index: 'status, rebuild',
      app: 'info',
      log: 'renderer-error',
      mcp: 'status',
      edit: 'undo',
    },
    events: [
      'menu:command',
      'app:notice',
      'settings:changed',
      'project:changed',
      'chat:event',
      'chat:snapshot',
      'history:changed',
      'terminal:data',
      'terminal:exit',
      'panel:show',
    ],
  },
  chatEvents: {
    User: ['user'],
    'Assistant text': ['assistant-start', 'assistant-delta', 'thinking-delta', 'assistant-restart', 'assistant-end'],
    Tools: ['tool-start', 'tool-running', 'tool-progress', 'tool-end', 'tool-undone'],
    Messages: ['error', 'notice'],
    State: ['busy', 'resumable', 'usage', 'title'],
  },
  tools: [
    ['read_file', 'files.ts', 0, 0, 'always'],
    ['list_directory', 'files.ts', 0, 0, 'always'],
    ['grep', 'files.ts', 0, 0, 'always'],
    ['glob', 'glob.ts', 0, 0, 'always'],
    ['edit_file', 'files.ts', 1, 0, 'always'],
    ['write_file', 'files.ts', 1, 0, 'always'],
    ['apply_patch', 'apply_patch.ts', 1, 0, 'always'],
    ['run_command', 'shell.ts', 1, 0, 'always'],
    ['command_output', 'shell.ts', 0, 0, 'always'],
    ['fetch_url', 'web.ts', 1, 0, 'always'],
    ['web_search', 'web.ts', 0, 0, 'web search provider set'],
    ['browser', 'browser.ts', 1, 0, 'browser panel available'],
    ['propose_plan', 'plan.ts', 1, 1, 'always (asks only while plan mode is on)'],
    ['load_skill', 'skills.ts', 0, 0, 'project has skills'],
    ['search_code', 'search/code_index.ts', 0, 0, 'code index available (per chat)'],
    ['task', 'task.ts', 0, 0, 'per chat (subagent)'],
    ['finder', 'task.ts', 0, 0, 'per chat (subagent)'],
    ['oracle', 'task.ts', 0, 0, 'per chat (subagent)'],
    ['todo_list', 'todo.ts', 0, 0, 'per chat'],
    ['mcp_<server>_<tool>', 'mcp.ts (McpHub)', 1, 1, 'one per MCP server tool'],
  ],
  readOnly: ['read_file', 'list_directory', 'grep', 'glob', 'search_code', 'load_skill'],
  npmDeps: 9,
  npmDev: 28,
  models: {
    anthropic: [
      'claude-opus-5-5 (default)',
      'claude-sonnet-5-5 (mid)',
      'claude-haiku-5-5 (small)',
      'claude-fable-5-1',
      'claude-haiku-4-5 (legacy)',
    ],
    openai: ['gpt-6-astra', 'gpt-6.1-sol (mid)', 'gpt-6-sol (legacy)', 'gpt-6-luna (small)'],
  },
  testsByArea: [
    { a: 'main/agent', f: 11, c: 265, src: 1887, tl: 3828 },
    { a: 'main/llm', f: 8, c: 112, src: 2218, tl: 3114 },
    { a: 'main/tools', f: 30, c: 710, src: 6085, tl: 9121 },
    { a: 'main/panels', f: 4, c: 82, src: 802, tl: 1282 },
    { a: 'main/other', f: 15, c: 235, src: 3772, tl: 3624 },
    { a: 'shared', f: 8, c: 94, src: 1379, tl: 1089 },
    { a: 'renderer', f: 7, c: 23, src: 6653, tl: 242 },
    { a: 'preload', f: 0, c: 0, src: 37, tl: 0 },
  ],
  e2e: [
    ['security', 13],
    ['chat', 13],
    ['ui', 12],
    ['panels', 9],
    ['sandbox_approvals', 9],
    ['logging', 5],
    ['compact', 4],
    ['project_settings', 4],
    ['project_switching', 7],
    ['settings', 7],
    ['undo', 4],
    ['images', 4],
    ['projects', 3],
    ['retry', 3],
    ['transcript_view', 6],
    ['crash_kill', 2],
    ['documentation-visuals', 2],
    ['large_output', 2],
    ['long_run', 2],
    ['openai_responses', 4],
    ['secrets_restart', 2],
    ['chat_controls', 8],
    ['crash_resume', 1],
    ['grep_redos', 1],
    ['mcp', 2],
    ['git_init', 1],
    ['plan_mode', 1],
    ['resume', 1],
    ['single_instance', 1],
    ['skills', 1],
    ['task', 1],
    ['terminal_no_project', 1],
    ['planted_binaries', 1],
  ],
  untested: [
    [865, 'renderer/src/app.ts'],
    [764, 'renderer/src/views/dialogs.ts'],
    [749, 'renderer/src/views/panels.ts'],
    [625, 'main/index.ts'],
    [393, 'main/tools/files.ts *'],
    [202, 'shared/ipc.ts'],
  ],
  largest: [
    [865, 'renderer/src/app.ts'],
    [764, 'renderer/src/views/dialogs.ts'],
    [749, 'renderer/src/views/panels.ts'],
    [746, 'main/tools/shell.ts'],
    [654, 'main/tools/sandbox.ts'],
    [625, 'main/index.ts'],
    [602, 'renderer/src/views/transcript.ts'],
    [596, 'main/agent/agent.ts'],
    [551, 'main/search/code_index.ts'],
    [547, 'main/chat_manager.ts'],
    [526, 'main/agent/session.ts'],
    [507, 'main/llm/codex_auth.ts'],
    [507, 'main/panels/git.ts'],
    [484, 'main/settings.ts'],
    [459, 'main/llm/anthropic.ts'],
  ],
  docs: [
    ['docs/PERFORMANCE.md', 461],
    ['docs/USAGE.md', 303],
    ['docs/ARCHITECTURE.md', 263],
    ['docs/DEVELOPMENT.md', 215],
    ['CHANGELOG.md', 243],
    ['README.md', 147],
    ['AGENTS.md', 77],
    ['CONTRIBUTING.md', 33],
    ['LICENSE (Apache-2.0, with the historical MIT notice)', 233],
  ],
  commitsByDay: [
    ['2024-07-29', 3],
    ['2026-09-29', 67],
    ['2026-09-30', 99],
    ['2026-10-01', 33],
    ['2026-10-02', 15],
    ['2026-10-03', 24],
    ['2026-10-04', 32],
    ['2026-10-05', 17],
    ['2026-10-06', 43],
    ['2026-10-07', 20],
    ['2026-10-08', 65],
    ['2026-10-09', 91],
  ],
  types: [
    ['fix', 212],
    ['docs', 90],
    ['feat', 70],
    ['test', 54],
    ['chore', 31],
    ['perf', 21],
    ['ci', 13],
    ['other', 8],
    ['refactor', 6],
    ['build', 3],
    ['security', 1],
  ],
  authors: [
    ['PierrunoYT', 415],
    ['Amp', 52],
    ['StepUpGaming', 23],
    ['Huanyi Xie', 7],
    ['Claude', 7],
    ['Steven Isaac', 3],
    ['reason-machines[bot]', 1],
    ['patchmote[bot]', 1],
  ],
  churn: [
    ['CHANGELOG.md', 323],
    ['docs/ARCHITECTURE.md', 204],
    ['docs/DEVELOPMENT.md', 128],
    ['project-map/data.js', 127],
    ['README.md', 127],
    ['docs/USAGE.md', 96],
    ['TASKS.md (no longer tracked)', 83],
    ['src/main/index.ts', 61],
    ['patch-overview.html (now project-map/)', 52],
    ['package.json', 51],
    ['project-map/views/10-focus.js', 50],
    ['src/main/chat_manager.ts', 49],
    ['src/main/agent/agent.ts', 41],
    ['src/main/tools/tools.test.ts', 38],
    ['src/main/tools/shell.ts', 37],
    ['src/renderer/src/views/dialogs.ts', 35],
    ['src/renderer/src/app.ts', 34],
    ['src/main/agent/session.ts', 30],
    ['docs/PERFORMANCE.md', 29],
    ['src/main/agent/agent.test.ts', 28],
  ],
  recent: [
    ['6bfbb71', "docs: refresh the project map's sizes, test counts, history and Focus after the Oct 9 fixes"],
    ['16e6cb9', 'docs: narrow #259 in the project map to the native helper item still open'],
    ['eb5a878', 'fix(apply_patch): refuse new names Windows rejects, and case-only duplicates, up front'],
    ['d681753', 'docs: Git panel commits run no hooks, and MCP servers follow project switches'],
    ['fb896c6', 'fix(storage): flush JSON files to disk before renaming them into place'],
    ['d1e955c', 'fix(mcp): close a server that finishes starting after the hub stopped'],
    ['a2ae51e', 'fix(search): keep files named like Object properties in the index'],
    ['de0789b', 'fix(git): leave a new link outside the project out of the panel diff'],
    ['11a1418', 'fix(terminal): drop output from a shell that was already replaced'],
    ['770cbe9', 'docs: track the DNS follow-up to #235 (#260)'],
    ['40df2a0', 'fix(security): keep a public page in the agent browser off local addresses'],
    ['20e224d', 'fix(plan): ask before changes in plan mode until a plan is approved'],
    ['25acb7f', 'fix(security): match permission rules against normalized paths, patch files and command parts'],
    ['3cf4e73', 'test(e2e): find the model overlay span by its text now that its class is removed'],
    ['432497b', 'fix(sandbox): relay a CONNECT tunnel only for TLS that names the checked host'],
    ['e3ee46e', "fix(settings): do not call keys encrypted under Linux's basic_text storage"],
    ['cac1df5', 'fix(search): stop a running index update when the embedding key changes'],
    ['f59de84', 'fix(mcp): start a server that stopped on its own again'],
    ['585fbac', 'fix(security): redact command output before shortening it, and as it streams'],
    ['a09f8f2', 'fix(security): strip classes, ids and hidden from model-written Markdown'],
    ['e578249', "fix(mcp): check a sandboxed server's project against the app's own folders"],
    ['9812676', 'fix(edit_file): refuse an edit when the file changed after its approved diff'],
    ['723d4ee', 'fix(security): count NAT64, 6to4 and reserved ranges as local addresses'],
    ['0d362f3', "fix(apply_patch): keep the file's own context lines when a hunk matches loosely"],
    ['3152c7b', "fix(openai): treat a call followed by the model's message as pending in Responses chats"],
    ['c87e628', 'fix(chats): skip a damaged chat file when rebuilding the chat list'],
    ['2b75ed1', 'fix(retry): wait at least a second for any Retry-After, and resume after long ones'],
    ['50296d5', 'fix(search): leave out a file that vanishes or cannot be read during indexing'],
    ['4d26788', "fix(git): check a new file's size before reading it for the Git panel's line counts"],
    ['808bb54', "docs: put the new MCP and Initialize e2e tests in the project map's e2e counts"],
    ['9c39ae0', 'fix(sandbox): stop sandboxed processes in the project before Git panel Initialize'],
    ['0801878', 'fix(security): keep credential files and secrets out of the search index uploads'],
    ['ee932d9', 'docs: count the new panels e2e test in the project map, not the panels area'],
    ['9d357d7', 'fix(security): take the agent browser offline while it shows a project file'],
    ['a18c30d', "fix(mcp): reconnect ${project} servers when History opens another project's chat"],
    ['2ea2768', 'fix(security): confirm removing or bypassing a delegate permission rule'],
    ['711cd67', 'fix(security): protect AGENTS.md, skills and auto-run configs from unreviewed edits'],
    ['65c6d4e', 'fix(security): ask before allowed commands that write files or run programs'],
  ],
  issues: [
    [259, 'Windows file helper truncates before writing; a crash can leave a short file', 'sandbox', 'low', 0, '10-09'],
    [257, 'macOS sandbox may allow hard links past hidden home and read-only .git', 'sandbox', 'low', 0, '10-09'],
    [240, 'A request the API rejects (400/413) keeps its message and breaks the chat', 'other', 'high', 0, '10-09'],
    [232, 'macOS sandbox lets commands read and write other terminals’ ttys', 'sandbox', 'high', 0, '10-09'],
    [228, 'Windows sandbox: share one drive letter per project, drop the temp drive', 'sandbox', 'low', 0, '10-09'],
    [
      227,
      'Windows sandbox: use the OS process security environment (PSEC) where available',
      'sandbox',
      'low',
      0,
      '10-09',
    ],
    [226, 'Evaluate Microsoft Execution Containers (MXC) as the command sandbox backend', 'sandbox', 'low', 0, '10-09'],
    [218, 'e2e: macOS UI and project-tab tests time out intermittently on CI', 'tests', 'low', 0, '10-08'],
    [207, 'Windows sandbox: toolchain access granted on the shared Program Files folder', 'sandbox', 'low', 0, '10-07'],
    [196, 'Test gaps from the code review: fakes, snapshot-only e2e checks, sleeps', 'tests', 'low', 0, '10-07'],
    [158, 'Windows sandbox hardening: LPAC, separate desktop, safe DLL search', 'sandbox', 'low', 0, '10-07'],
    [153, 'Environment scrubbing and secret redaction are deny-lists', 'security', 'low', 0, '10-07'],
    [150, 'Windows sandbox: memory and CPU limits apply per process, not per job', 'sandbox', 'low', 0, '10-07'],
    [149, 'Packaged builds run sandbox-helper.exe without checking its signature', 'sandbox', 'low', 0, '10-07'],
    [
      140,
      'Windows sandbox: files moved into a project lack its write grant until reopened',
      'sandbox',
      'low',
      0,
      '10-07',
    ],
    [139, 'Windows sandbox: .git permissions are still walked several times per command', 'sandbox', 'low', 0, '10-07'],
    [
      138,
      'e2e: crash_kill approval test stalls on CI (chat save and Local State never written)',
      'tests',
      'medium',
      0,
      '10-07',
    ],
    [135, 'Agent benchmark: a current baseline, more runs per task and regression checks', 'tests', 'low', 0, '10-06'],
    [128, 'Isolate built-in file tools behind an OS-restricted executor', 'sandbox', 'medium', 0, '10-06'],
    [127, 'Protect agent, IDE and shell configuration from command writes', 'sandbox', 'medium', 0, '10-06'],
    [126, 'Approve per-command read-only and read/write path grants', 'sandbox', 'low', 0, '10-06'],
    [121, 'Perplexity Decider V1 27B (OpenRouter) as a safety check on tool calls', 'tools', 'low', 0, '10-05'],
    [105, 'Plan-mode benchmark: multi-step tasks, a mid-run toggle, more models', 'tests', 'low', 0, '10-05'],
    [
      104,
      'No process or memory limits for Seatbelt commands on macOS (Linux and containers done)',
      'sandbox',
      'low',
      0,
      '10-05',
    ],
    [101, 'npm test fails and node --test hangs inside the AppContainer', 'sandbox', 'medium', 0, '10-05'],
    [
      97,
      'Enforce hostname restrictions on macOS and containers (Linux and Windows done)',
      'sandbox',
      'low',
      0,
      '10-04',
    ],
    [96, 'Narrow macOS sandbox file access, isolate command temp directories', 'sandbox', 'medium', 0, '10-04'],
    [87, 'Sandbox MCP stdio servers on macOS (Linux and Windows opt-in done)', 'mcp', 'low', 0, '10-04'],
    [85, 'Smarter context: tell the agent what changed since its last turn', 'tools', 'low', 0, '10-03'],
    [84, 'Smarter over time: a project memory the agent can propose additions to', 'tools', 'low', 0, '10-03'],
    [83, 'Smarter finish: review the changes before saying the turn is done', 'tools', 'low', 0, '10-03'],
    [82, 'Smarter navigation: go-to-definition and find-references tools', 'tools', 'low', 0, '10-03'],
    [81, 'Smarter edits: show new compiler and linter errors after each edit', 'tools', 'low', 0, '10-03'],
    [79, 'Faster turns: lower reasoning effort for subagents and simple requests', 'perf', 'low', 0, '10-03'],
    [78, 'Cheaper subagents: run task and oracle on a mid-size model', 'perf', 'low', 0, '10-03'],
    [74, 'Decide whether the release dry run should run on every push to main', 'release', 'low', 0, '10-03'],
    [71, 'Sign and notarize the macOS build', 'release', 'low', 0, '10-01'],
    [49, 'Agent benchmark: per-tool breakdown, other models, harder tasks', 'tests', 'low', 0, '10-01'],
    [46, 'Encourage batching independent tool calls (partly addressed in dfd1f07)', 'perf', 'low', 0, '10-01'],
    [37, 'Security lint rules, coverage, hostile-repo test', 'tests', 'low', 0, '09-30'],
    [28, 'macOS entitlements allow DYLD injection/unsigned exec memory', 'security', 'medium', 0, '09-30'],
    [26, 'Windows builds unsigned (workflow ready, waiting on certificate)', 'release', 'medium', 0, '09-30'],
    [22, 'Hand-test the macOS build and the deb on a real Ubuntu desktop', 'release', 'low', 0, '09-30'],
    [21, 'a11y: test with a real screen reader (NVDA)', 'ui', 'low', 0, '09-30'],
  ],
  themes: {
    sandbox: 'Command sandbox',
    security: 'Security & permissions',
    release: 'Packaging, release & CI',
    tests: 'Tests & benchmarks',
    perf: 'Performance',
    ui: 'UI / UX',
    tools: 'Tools',
    mcp: 'MCP',
    other: 'Bugs',
    docs: 'Docs & naming',
  },
  closedCount: 182,
};
// src/renderer/src/styles.css, counted with the renderer's source lines.
const RENDERER_CSS_LINES = 2797;
// Source lines of one process (renderer, preload, main, shared), summed from its areas.
const procLines = (proc) => D.areas.filter((a) => a.proc === proc).reduce((sum, a) => sum + a.lines, 0);
