/**
 * Ported from aider/special.py at revision
 * 5dc9490bb35f9729ef2c95d00a19ccd30c26339c.
 * Modified for Patch: paths are the repository-relative, forward-slash form the
 * rest of the map already uses, so no per-platform normalization is needed.
 * Licensed under the Apache License, Version 2.0.
 */

/**
 * Files that orient a reader in an unfamiliar repository — what it is, how it
 * builds, how it ships — and are worth a place in the map before any ranked
 * symbol.
 */
const ROOT_IMPORTANT_FILES: readonly string[] = [
  ".gitignore",
  ".gitattributes",
  "README",
  "README.md",
  "README.txt",
  "README.rst",
  "CONTRIBUTING",
  "CONTRIBUTING.md",
  "CONTRIBUTING.txt",
  "CONTRIBUTING.rst",
  "LICENSE",
  "LICENSE.md",
  "LICENSE.txt",
  "CHANGELOG",
  "CHANGELOG.md",
  "CHANGELOG.txt",
  "CHANGELOG.rst",
  "SECURITY",
  "SECURITY.md",
  "SECURITY.txt",
  "CODEOWNERS",
  "requirements.txt",
  "Pipfile",
  "Pipfile.lock",
  "pyproject.toml",
  "setup.py",
  "setup.cfg",
  "package.json",
  "package-lock.json",
  "yarn.lock",
  "npm-shrinkwrap.json",
  "Gemfile",
  "Gemfile.lock",
  "composer.json",
  "composer.lock",
  "pom.xml",
  "build.gradle",
  "build.gradle.kts",
  "build.sbt",
  "go.mod",
  "go.sum",
  "Cargo.toml",
  "Cargo.lock",
  "mix.exs",
  "rebar.config",
  "project.clj",
  "Podfile",
  "Cartfile",
  "dub.json",
  "dub.sdl",
  ".env",
  ".env.example",
  ".editorconfig",
  "tsconfig.json",
  "jsconfig.json",
  ".babelrc",
  "babel.config.js",
  ".eslintrc",
  ".eslintignore",
  ".prettierrc",
  ".stylelintrc",
  "tslint.json",
  ".pylintrc",
  ".flake8",
  ".rubocop.yml",
  ".scalafmt.conf",
  ".dockerignore",
  ".gitpod.yml",
  "sonar-project.properties",
  "renovate.json",
  "dependabot.yml",
  ".pre-commit-config.yaml",
  "mypy.ini",
  "tox.ini",
  ".yamllint",
  "pyrightconfig.json",
  "webpack.config.js",
  "rollup.config.js",
  "parcel.config.js",
  "gulpfile.js",
  "Gruntfile.js",
  "build.xml",
  "build.boot",
  "project.json",
  "build.cake",
  "MANIFEST.in",
  "pytest.ini",
  "phpunit.xml",
  "karma.conf.js",
  "jest.config.js",
  "cypress.json",
  ".nycrc",
  ".nycrc.json",
  ".travis.yml",
  ".gitlab-ci.yml",
  "Jenkinsfile",
  "azure-pipelines.yml",
  "bitbucket-pipelines.yml",
  "appveyor.yml",
  "circle.yml",
  ".circleci/config.yml",
  ".github/dependabot.yml",
  "codecov.yml",
  ".coveragerc",
  "Dockerfile",
  "docker-compose.yml",
  "docker-compose.override.yml",
  "serverless.yml",
  "firebase.json",
  "now.json",
  "netlify.toml",
  "vercel.json",
  "app.yaml",
  "terraform.tf",
  "main.tf",
  "cloudformation.yaml",
  "cloudformation.json",
  "ansible.cfg",
  "kubernetes.yaml",
  "k8s.yaml",
  "schema.sql",
  "liquibase.properties",
  "flyway.conf",
  "next.config.js",
  "nuxt.config.js",
  "vue.config.js",
  "angular.json",
  "gatsby-config.js",
  "gridsome.config.js",
  "swagger.yaml",
  "swagger.json",
  "openapi.yaml",
  "openapi.json",
  ".nvmrc",
  ".ruby-version",
  ".python-version",
  "Vagrantfile",
  ".codeclimate.yml",
  "mkdocs.yml",
  "_config.yml",
  "book.toml",
  "readthedocs.yml",
  ".readthedocs.yaml",
  ".npmrc",
  ".yarnrc",
  ".isort.cfg",
  ".markdownlint.json",
  ".markdownlint.yaml",
  ".bandit",
  ".secrets.baseline",
  ".pypirc",
  ".gitkeep",
  ".npmignore",
];

const IMPORTANT = new Set(ROOT_IMPORTANT_FILES);

/**
 * `path` is repository-relative with forward slashes, as every other map input
 * is. Only the repository root counts: a `README.md` beside some source file
 * describes that directory, not the project.
 */
export function isImportantFile(path: string): boolean {
  if (IMPORTANT.has(path)) return true;
  // Workflow definitions are named freely, so they are matched by location.
  return /^\.github\/workflows\/[^/]+\.ya?ml$/u.test(path);
}

export function filterImportantFiles(
  paths: readonly string[],
): readonly string[] {
  return paths.filter((path) => isImportantFile(path));
}
